# Generated by Django 3.2.9 on 2021-12-05 00:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True)),
                ('height', models.IntegerField(blank=True, default=100, null=True)),
                ('padding', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('auto', 'auto')], default=0, null=True)),
                ('margin', models.IntegerField(blank=True, default=0, null=True)),
                ('bg_color', models.CharField(blank=True, choices=[('bg-primary', 'blue'), ('bg-secondary', 'grey'), ('bg-success', 'green'), ('bg-danger', 'red'), ('bg-warning', 'yellow'), ('bg-info', 'lightblue'), ('bg-light', 'light'), ('bg-dark', 'dark'), ('bg-body', 'body'), ('bg-white', 'white'), ('bg-transparent', 'transparent')], max_length=15, null=True)),
                ('bg_gradient', models.BooleanField(blank=True, default=False, null=True)),
                ('position', models.CharField(blank=True, choices=[('position-static', 'static'), ('bottom', 'fixed-bottom'), ('sticky-top', 'sticky-top')], max_length=20, null=True)),
                ('top', models.IntegerField(blank=True, default=0, null=True)),
                ('left', models.IntegerField(blank=True, default=0, null=True)),
                ('down', models.IntegerField(blank=True, default=0, null=True)),
                ('right', models.IntegerField(blank=True, default=0, null=True)),
                ('display', models.CharField(blank=True, choices=[('none', 'none'), ('inline', 'inline'), ('block', 'block'), ('flex', 'flex')], default='', max_length=50, null=True)),
                ('direction', models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='', max_length=20)),
                ('align_items', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('baseline', '-baseline'), ('stretch', '-stretch')], default='', max_length=10)),
                ('align_content', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('around', '-around'), ('stretch', '-stretch')], default='', max_length=10)),
                ('flex_grow', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('breakpoint', models.CharField(blank=True, choices=[('sm', '-sm'), ('md', '-md'), ('lg', '-lg'), ('xl', '-xl'), ('xxl', '-xxl'), ('fluid', '-fluid')], default='', max_length=10)),
                ('align_self', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end')], default='', max_length=10)),
                ('justify_content', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('around', '-around'), ('between', '-between'), ('evenly', '-evenly')], default='', max_length=10)),
                ('dimension', models.PositiveIntegerField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True)),
                ('height', models.IntegerField(blank=True, default=100, null=True)),
                ('padding', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('auto', 'auto')], default=0, null=True)),
                ('margin', models.IntegerField(blank=True, default=0, null=True)),
                ('breakpoint', models.CharField(blank=True, choices=[('sm', '-sm'), ('md', '-md'), ('lg', '-lg'), ('xl', '-xl'), ('xxl', '-xxl'), ('fluid', '-fluid')], default='', max_length=10)),
                ('bg_color', models.CharField(blank=True, choices=[('bg-primary', 'blue'), ('bg-secondary', 'grey'), ('bg-success', 'green'), ('bg-danger', 'red'), ('bg-warning', 'yellow'), ('bg-info', 'lightblue'), ('bg-light', 'light'), ('bg-dark', 'dark'), ('bg-body', 'body'), ('bg-white', 'white'), ('bg-transparent', 'transparent')], max_length=15, null=True)),
                ('bg_gradient', models.BooleanField(blank=True, default=False, null=True)),
                ('position', models.CharField(blank=True, choices=[('position-static', 'static'), ('bottom', 'fixed-bottom'), ('sticky-top', 'sticky-top')], max_length=20, null=True)),
                ('top', models.IntegerField(blank=True, default=0, null=True)),
                ('left', models.IntegerField(blank=True, default=0, null=True)),
                ('down', models.IntegerField(blank=True, default=0, null=True)),
                ('right', models.IntegerField(blank=True, default=0, null=True)),
                ('display', models.CharField(blank=True, choices=[('none', 'none'), ('inline', 'inline'), ('block', 'block'), ('flex', 'flex')], default='', max_length=50, null=True)),
                ('direction', models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='', max_length=20)),
                ('justify_content', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('around', '-around'), ('between', '-between'), ('evenly', '-evenly')], default='', max_length=10)),
                ('align_items', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('baseline', '-baseline'), ('stretch', '-stretch')], default='', max_length=10)),
                ('align_self', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('baseline', '-baseline'), ('stretch', '-stretch')], default='', max_length=10)),
                ('align_content', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('around', '-around'), ('stretch', '-stretch')], default='', max_length=10)),
                ('flex_grow', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default=models.CharField(blank=True, max_length=100, unique=True), max_length=100)),
                ('has_navBar', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.col')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True)),
                ('height', models.IntegerField(blank=True, default=100, null=True)),
                ('padding', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('auto', 'auto')], default=0, null=True)),
                ('margin', models.IntegerField(blank=True, default=0, null=True)),
                ('bg_color', models.CharField(blank=True, choices=[('bg-primary', 'blue'), ('bg-secondary', 'grey'), ('bg-success', 'green'), ('bg-danger', 'red'), ('bg-warning', 'yellow'), ('bg-info', 'lightblue'), ('bg-light', 'light'), ('bg-dark', 'dark'), ('bg-body', 'body'), ('bg-white', 'white'), ('bg-transparent', 'transparent')], max_length=15, null=True)),
                ('bg_gradient', models.BooleanField(blank=True, default=False, null=True)),
                ('position', models.CharField(blank=True, choices=[('position-static', 'static'), ('bottom', 'fixed-bottom'), ('sticky-top', 'sticky-top')], max_length=20, null=True)),
                ('top', models.IntegerField(blank=True, default=0, null=True)),
                ('left', models.IntegerField(blank=True, default=0, null=True)),
                ('down', models.IntegerField(blank=True, default=0, null=True)),
                ('right', models.IntegerField(blank=True, default=0, null=True)),
                ('display', models.CharField(blank=True, choices=[('none', 'none'), ('inline', 'inline'), ('block', 'block'), ('flex', 'flex')], default='', max_length=50, null=True)),
                ('direction', models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='', max_length=20)),
                ('align_self', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('baseline', '-baseline'), ('stretch', '-stretch')], default='', max_length=10)),
                ('align_content', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('around', '-around'), ('stretch', '-stretch')], default='', max_length=10)),
                ('flex_grow', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('breakpoint', models.CharField(blank=True, choices=[('sm', '-sm'), ('md', '-md'), ('lg', '-lg'), ('xl', '-xl'), ('xxl', '-xxl'), ('fluid', '-fluid')], default='', max_length=10)),
                ('align_items', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end')], default='', max_length=10)),
                ('justify_content', models.CharField(blank=True, choices=[('start', '-start'), ('center', '-center'), ('end', '-end'), ('around', '-around'), ('between', '-between'), ('evenly', '-evenly')], default='', max_length=10)),
                ('order', models.IntegerField()),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.col')),
            ],
        ),
        migrations.AddField(
            model_name='col',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.row'),
        ),
    ]
