# Generated by Django 3.2.9 on 2021-12-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='align_content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='align_items',
        ),
        migrations.RemoveField(
            model_name='section',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='section',
            name='display',
        ),
        migrations.RemoveField(
            model_name='section',
            name='height',
        ),
        migrations.RemoveField(
            model_name='section',
            name='justify_content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='section',
            name='padding',
        ),
        migrations.RemoveField(
            model_name='section',
            name='width',
        ),
        migrations.AlterField(
            model_name='container',
            name='images',
            field=models.ManyToManyField(blank=True, to='Acms.Image'),
        ),
        migrations.AlterField(
            model_name='container',
            name='texts',
            field=models.ManyToManyField(blank=True, to='Acms.Text'),
        ),
    ]
