# Generated by Django 3.2.9 on 2022-02-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='navbar',
        ),
        migrations.AddField(
            model_name='navbar',
            name='pages_with_navbar',
            field=models.ManyToManyField(blank=True, to='Acms.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='footer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.footer'),
        ),
    ]
