# Generated by Django 3.2.9 on 2021-12-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='overlay',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
