# Generated by Django 3.2.9 on 2021-11-23 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageindex',
            name='content',
        ),
        migrations.CreateModel(
            name='BlockSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acms.pageindex')),
            ],
        ),
    ]
