# Generated by Django 3.2.9 on 2021-12-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='col',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='col',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='height',
            field=models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='margin',
            field=models.IntegerField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('auto', 'auto')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='padding',
            field=models.IntegerField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('auto', 'auto')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='height',
            field=models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='margin',
            field=models.IntegerField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('auto', 'auto')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='padding',
            field=models.IntegerField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('auto', 'auto')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='row',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='row',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='height',
            field=models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='margin',
            field=models.IntegerField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('auto', 'auto')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='padding',
            field=models.IntegerField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('auto', 'auto')], default=0, null=True),
        ),
    ]
