# Generated by Django 3.2.9 on 2021-12-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0002_auto_20211226_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='height',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='width',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
