# Generated by Django 3.2.9 on 2021-12-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0002_auto_20211219_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default=0, max_length=5, null=True),
        ),
    ]
