# Generated by Django 3.2.9 on 2021-12-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0002_auto_20211227_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='', help_text='\n            align all the  content\n            on the cross axis if there is space \n        ', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', help_text='\n            alignment of content on the cross axis:\n            y if direction is row;\n            x if direction is column.\n        ', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='height',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='', help_text='\n            alignment of content on the main axis:\n            x if direction is row;\n            y if direction is column.\n        ', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-auto', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-auto', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='width',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
