# Generated by Django 3.2.9 on 2022-02-12 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0002_auto_20220212_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='pages_with_navbar',
        ),
        migrations.AddField(
            model_name='page',
            name='navbar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.navbar'),
        ),
    ]
