# Generated by Django 3.2.9 on 2021-12-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0003_auto_20211226_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlay',
            name='height',
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='width',
        ),
        migrations.AlterField(
            model_name='container',
            name='flex_grow',
            field=models.IntegerField(blank=True, default='', help_text='\n        \n        ', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='flex_grow',
            field=models.IntegerField(blank=True, default='', help_text='\n        \n        ', null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='flex_grow',
            field=models.IntegerField(blank=True, default='', help_text='\n        \n        ', null=True),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='flex_grow',
            field=models.IntegerField(blank=True, default='', help_text='\n        \n        ', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='flex_grow',
            field=models.IntegerField(blank=True, default='', help_text='\n        \n        ', null=True),
        ),
    ]
