# Generated by Django 3.2.9 on 2021-11-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0003_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, default=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Texts',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='blocksection',
            old_name='content',
            new_name='name',
        ),
        migrations.AddField(
            model_name='blocksection',
            name='position',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='blocksection',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acms.page'),
        ),
        migrations.DeleteModel(
            name='PageIndex',
        ),
    ]
