# Generated by Django 3.2.9 on 2021-12-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0003_auto_20211227_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='logo',
        ),
        migrations.AddField(
            model_name='footer',
            name='logo',
            field=models.ManyToManyField(to='Acms.Text'),
        ),
        migrations.RemoveField(
            model_name='link',
            name='container',
        ),
        migrations.AddField(
            model_name='link',
            name='container',
            field=models.ManyToManyField(to='Acms.Container'),
        ),
        migrations.RemoveField(
            model_name='link',
            name='overlay',
        ),
        migrations.AddField(
            model_name='link',
            name='overlay',
            field=models.ManyToManyField(to='Acms.Overlay'),
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='container',
        ),
        migrations.AddField(
            model_name='overlay',
            name='container',
            field=models.ManyToManyField(blank=True, to='Acms.Container'),
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='section',
        ),
        migrations.AddField(
            model_name='overlay',
            name='section',
            field=models.ManyToManyField(blank=True, to='Acms.Section'),
        ),
    ]
