# Generated by Django 3.2.9 on 2022-02-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0003_auto_20220212_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.footer'),
        ),
        migrations.AlterField(
            model_name='page',
            name='navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.navbar'),
        ),
    ]
