# Generated by Django 3.2.9 on 2021-11-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0004_auto_20211123_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
