# Generated by Django 3.2.9 on 2022-02-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0004_auto_20220212_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='has_user_functionality',
            field=models.BooleanField(default=False),
        ),
    ]
