# Generated by Django 3.2.9 on 2021-12-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0004_auto_20211226_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='alignment',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='color',
            field=models.CharField(blank=True, choices=[('-primary', 'blue'), ('-secondary', 'grey'), ('-success', 'green'), ('-danger', 'red'), ('-warning', 'yellow'), ('-info', 'lightblue'), ('-light', 'light'), ('-dark', 'dark'), ('-body', 'body'), ('-muted', 'muted'), ('-white', 'white'), ('-black', 'black')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='italics',
            field=models.CharField(blank=True, choices=[('-italic', 'italic'), ('-normal', 'normal')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='line_height',
            field=models.CharField(blank=True, choices=[('-sm', 'small'), ('-base', 'normal'), ('-lg', 'large')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='overflow',
            field=models.CharField(blank=True, choices=[('-auto', 'auto'), ('-hidden', 'hidden'), ('-visible', 'visible'), ('-scroll', 'scroll')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='size',
            field=models.CharField(blank=True, choices=[('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-6', '6')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text_decoration',
            field=models.CharField(blank=True, choices=[('-underline', 'underline'), ('-line-through', 'line through'), ('-none', 'none')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='vertical_align',
            field=models.CharField(blank=True, choices=[('-baseline', 'baseline'), ('-top', 'top'), ('-middle', 'middle'), ('-bottom', 'bottom'), ('-text-top', 'text-top'), ('-text-bottom', 'text-bottom')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='weight',
            field=models.CharField(blank=True, choices=[('-bold', 'bold'), ('-bolder', 'bolder'), ('-normal', 'normal'), ('-light', 'light'), ('-lighter', 'lighter')], max_length=15, null=True),
        ),
    ]
