# Generated by Django 3.2.9 on 2021-12-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0005_auto_20211227_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='logo',
        ),
        migrations.AddField(
            model_name='navbar',
            name='logo',
            field=models.ManyToManyField(to='Acms.Image'),
        ),
    ]
