# Generated by Django 3.2.9 on 2021-12-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0006_auto_20211219_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True)),
                ('height', models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True)),
                ('padding', models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default=0, max_length=5, null=True)),
                ('margin', models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default=0, max_length=5, null=True)),
                ('breakpoint', models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', max_length=10)),
                ('bg_color', models.CharField(blank=True, choices=[('bg-primary', 'blue'), ('bg-secondary', 'grey'), ('bg-success', 'green'), ('bg-danger', 'red'), ('bg-warning', 'yellow'), ('bg-info', 'lightblue'), ('bg-light', 'light'), ('bg-dark', 'dark'), ('bg-body', 'body'), ('bg-white', 'white'), ('bg-transparent', 'transparent'), ('', 'no bg color')], max_length=15, null=True)),
                ('bg_gradient', models.BooleanField(blank=True, default=False, null=True)),
                ('position', models.CharField(blank=True, choices=[('position-static', 'static'), ('bottom', 'fixed-bottom'), ('sticky-top', 'sticky-top')], max_length=20, null=True)),
                ('top', models.IntegerField(blank=True, default=0, null=True)),
                ('left', models.IntegerField(blank=True, default=0, null=True)),
                ('down', models.IntegerField(blank=True, default=0, null=True)),
                ('right', models.IntegerField(blank=True, default=0, null=True)),
                ('display', models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True)),
                ('direction', models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='', max_length=20)),
                ('justify_content', models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='', max_length=10)),
                ('align_items', models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10)),
                ('align_self', models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10)),
                ('align_content', models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='', max_length=10)),
                ('flex_grow', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='container',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.section'),
        ),
        migrations.AlterField(
            model_name='container',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
