# Generated by Django 3.2.9 on 2021-12-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0006_auto_20211227_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='page',
            new_name='pages',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='logo',
        ),
        migrations.AddField(
            model_name='footer',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.image'),
        ),
    ]
