# Generated by Django 4.0.2 on 2022-02-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0006_alter_navbar_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='grid',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='grid',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='borders',
            field=models.CharField(blank=True, choices=[('rounded', 'small rounding all corners'), ('rounded-top', 'small rounding top corners'), ('rounded-end', 'small rounding right corners'), ('rounded-bottom', 'small rounding bottom corners'), ('rounded-start', 'small rounding left corners'), ('rounded-circle', 'as a circle'), ('rounded-pill', 'in pill form'), ('', 'no rounding')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='borders_colors',
            field=models.CharField(blank=True, choices=[('border border-primary', 'blue'), ('border border-secondary', 'grey'), ('border border-success', 'green'), ('border border-danger', 'red'), ('border border-warning', 'yellow'), ('border border-info', 'cyan'), ('border border-light', 'light'), ('border border-dark', 'black'), ('border border-white', 'white '), ('', 'no border, no color')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='button',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='-center', help_text='\n            align all the  content\n            on the cross axis if there is space \n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='-center', help_text='\n            alignment of content on the cross axis:\n            y if direction is row;\n            x if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='row', max_length=20),
        ),
        migrations.AlterField(
            model_name='container',
            name='flex_wrap',
            field=models.CharField(blank=True, choices=[('-wrap', 'wrap'), ('-nowrap', 'no wrap'), ('-wrap-reverse', 'wrap reverse')], default='-nowrap', help_text='\n            wrap of the content inside flex container\n            in one row if no wrap\n            in multiple rows in wrap\n            multiple rows from bottom in wrap reverse\n        ', max_length=15),
        ),
        migrations.AlterField(
            model_name='container',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='-center', help_text='\n            alignment of content on the main axis:\n            x if direction is row;\n            y if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='-center', help_text='\n            align all the  content\n            on the cross axis if there is space \n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='footer',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='-center', help_text='\n            alignment of content on the cross axis:\n            y if direction is row;\n            x if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='footer',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='row', max_length=20),
        ),
        migrations.AlterField(
            model_name='footer',
            name='flex_wrap',
            field=models.CharField(blank=True, choices=[('-wrap', 'wrap'), ('-nowrap', 'no wrap'), ('-wrap-reverse', 'wrap reverse')], default='-nowrap', help_text='\n            wrap of the content inside flex container\n            in one row if no wrap\n            in multiple rows in wrap\n            multiple rows from bottom in wrap reverse\n        ', max_length=15),
        ),
        migrations.AlterField(
            model_name='footer',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='-center', help_text='\n            alignment of content on the main axis:\n            x if direction is row;\n            y if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='footer',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='footer',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='-center', help_text='\n            align all the  content\n            on the cross axis if there is space \n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='grid',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='-center', help_text='\n            alignment of content on the cross axis:\n            y if direction is row;\n            x if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='grid',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='row', max_length=20),
        ),
        migrations.AlterField(
            model_name='grid',
            name='flex_wrap',
            field=models.CharField(blank=True, choices=[('-wrap', 'wrap'), ('-nowrap', 'no wrap'), ('-wrap-reverse', 'wrap reverse')], default='-nowrap', help_text='\n            wrap of the content inside flex container\n            in one row if no wrap\n            in multiple rows in wrap\n            multiple rows from bottom in wrap reverse\n        ', max_length=15),
        ),
        migrations.AlterField(
            model_name='grid',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='-center', help_text='\n            alignment of content on the main axis:\n            x if direction is row;\n            y if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='grid',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='grid',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='-center', help_text='\n            align all the  content\n            on the cross axis if there is space \n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='-center', help_text='\n            alignment of content on the cross axis:\n            y if direction is row;\n            x if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='row', max_length=20),
        ),
        migrations.AlterField(
            model_name='link',
            name='flex_wrap',
            field=models.CharField(blank=True, choices=[('-wrap', 'wrap'), ('-nowrap', 'no wrap'), ('-wrap-reverse', 'wrap reverse')], default='-nowrap', help_text='\n            wrap of the content inside flex container\n            in one row if no wrap\n            in multiple rows in wrap\n            multiple rows from bottom in wrap reverse\n        ', max_length=15),
        ),
        migrations.AlterField(
            model_name='link',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='-center', help_text='\n            alignment of content on the main axis:\n            x if direction is row;\n            y if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='-center', help_text='\n            align all the  content\n            on the cross axis if there is space \n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='-center', help_text='\n            alignment of content on the cross axis:\n            y if direction is row;\n            x if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='row', max_length=20),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='flex_wrap',
            field=models.CharField(blank=True, choices=[('-wrap', 'wrap'), ('-nowrap', 'no wrap'), ('-wrap-reverse', 'wrap reverse')], default='-nowrap', help_text='\n            wrap of the content inside flex container\n            in one row if no wrap\n            in multiple rows in wrap\n            multiple rows from bottom in wrap reverse\n        ', max_length=15),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='-center', help_text='\n            alignment of content on the main axis:\n            x if direction is row;\n            y if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='-center', help_text='\n            align all the  content\n            on the cross axis if there is space \n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='-center', help_text='\n            alignment of content on the cross axis:\n            y if direction is row;\n            x if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='row', max_length=20),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='flex_wrap',
            field=models.CharField(blank=True, choices=[('-wrap', 'wrap'), ('-nowrap', 'no wrap'), ('-wrap-reverse', 'wrap reverse')], default='-nowrap', help_text='\n            wrap of the content inside flex container\n            in one row if no wrap\n            in multiple rows in wrap\n            multiple rows from bottom in wrap reverse\n        ', max_length=15),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='-center', help_text='\n            alignment of content on the main axis:\n            x if direction is row;\n            y if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='-center', help_text='\n            align all the  content\n            on the cross axis if there is space \n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='-center', help_text='\n            alignment of content on the cross axis:\n            y if direction is row;\n            x if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='row', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='flex_wrap',
            field=models.CharField(blank=True, choices=[('-wrap', 'wrap'), ('-nowrap', 'no wrap'), ('-wrap-reverse', 'wrap reverse')], default='-nowrap', help_text='\n            wrap of the content inside flex container\n            in one row if no wrap\n            in multiple rows in wrap\n            multiple rows from bottom in wrap reverse\n        ', max_length=15),
        ),
        migrations.AlterField(
            model_name='section',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='-center', help_text='\n            alignment of content on the main axis:\n            x if direction is row;\n            y if direction is column.\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='-100', max_length=10),
        ),
        migrations.AlterField(
            model_name='text',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='-0', max_length=5, null=True),
        ),
    ]
