# Generated by Django 4.0.2 on 2022-02-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0007_button_borders_button_borders_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='object_fit',
            field=models.CharField(blank=True, choices=[('contain', 'contain'), ('cover', 'cover'), ('fill', 'fill'), ('none', 'none'), ('scale-down', 'scale-down')], default='none', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='col',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=3, null=True),
        ),
    ]
