# Generated by Django 3.2.9 on 2021-12-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0007_auto_20211228_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='container',
            field=models.ManyToManyField(blank=True, to='Acms.Container'),
        ),
        migrations.AlterField(
            model_name='link',
            name='overlay',
            field=models.ManyToManyField(blank=True, to='Acms.Overlay'),
        ),
    ]
