# Generated by Django 3.2.9 on 2021-12-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0008_auto_20211219_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
