# Generated by Django 4.0.2 on 2022-02-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0009_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='texts',
            new_name='text',
        ),
    ]
