# Generated by Django 3.2.9 on 2021-11-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0009_auto_20211124_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('leftSide', 'leftSide'), ('rightSide', 'rightSide'), ('top', 'top'), ('down', 'down')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='has_navBar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
