# Generated by Django 3.2.9 on 2021-12-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0009_auto_20211228_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky'), ('', 'no specified position')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='footer',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky'), ('', 'no specified position')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky'), ('', 'no specified position')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='link',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky'), ('', 'no specified position')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky'), ('', 'no specified position')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky'), ('', 'no specified position')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky'), ('', 'no specified position')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='text',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky'), ('', 'no specified position')], default='', max_length=20),
        ),
    ]
