# Generated by Django 3.2.9 on 2021-12-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0009_auto_20211219_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='position',
        ),
        migrations.AddField(
            model_name='image',
            name='col',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.col'),
        ),
        migrations.AddField(
            model_name='image',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.container'),
        ),
    ]
