# Generated by Django 4.0.2 on 2022-02-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0010_rename_images_card_image_rename_texts_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='container',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='footer',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='grid',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='link',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='text',
            name='bg_gradient',
            field=models.CharField(blank=True, choices=[('bg-gradient', 'bottom-top gradient'), ('', 'no gradient')], default='', max_length=20),
        ),
    ]
