# Generated by Django 3.2.9 on 2021-12-19 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0010_auto_20211219_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='col',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.col'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
