# Generated by Django 3.2.9 on 2021-12-29 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0010_auto_20211228_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overlay',
            old_name='container',
            new_name='containers',
        ),
        migrations.RenameField(
            model_name='overlay',
            old_name='section',
            new_name='sections',
        ),
        migrations.RemoveField(
            model_name='container',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='link',
            name='align_content',
        ),
        migrations.RemoveField(
            model_name='link',
            name='align_items',
        ),
        migrations.RemoveField(
            model_name='link',
            name='container',
        ),
        migrations.RemoveField(
            model_name='link',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='link',
            name='flex_grow',
        ),
        migrations.RemoveField(
            model_name='link',
            name='flex_wrap',
        ),
        migrations.RemoveField(
            model_name='link',
            name='inline',
        ),
        migrations.RemoveField(
            model_name='link',
            name='justify_content',
        ),
        migrations.RemoveField(
            model_name='link',
            name='overlay',
        ),
        migrations.RemoveField(
            model_name='page',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='page',
            name='navbar',
        ),
        migrations.AddField(
            model_name='container',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.section'),
        ),
        migrations.AddField(
            model_name='footer',
            name='pages',
            field=models.ManyToManyField(to='Acms.Page'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='pages',
            field=models.ManyToManyField(to='Acms.Page'),
        ),
        migrations.AlterField(
            model_name='container',
            name='align_self',
            field=models.CharField(choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='breakpoint',
            field=models.CharField(choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), (None, 'no breakpoint')], default=None, help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AlterField(
            model_name='container',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='align_self',
            field=models.CharField(choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='footer',
            name='breakpoint',
            field=models.CharField(choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), (None, 'no breakpoint')], default=None, help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='align_self',
            field=models.CharField(choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='breakpoint',
            field=models.CharField(choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), (None, 'no breakpoint')], default=None, help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='align_self',
            field=models.CharField(choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='breakpoint',
            field=models.CharField(choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), (None, 'no breakpoint')], default=None, help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='align_self',
            field=models.CharField(choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='breakpoint',
            field=models.CharField(choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), (None, 'no breakpoint')], default=None, help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='align_self',
            field=models.CharField(choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='breakpoint',
            field=models.CharField(choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), (None, 'no breakpoint')], default=None, help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='align_self',
            field=models.CharField(choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='breakpoint',
            field=models.CharField(choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), (None, 'no breakpoint')], default=None, help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='align_self',
            field=models.CharField(choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='text',
            name='breakpoint',
            field=models.CharField(choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), (None, 'no breakpoint')], default=None, help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AlterField(
            model_name='text',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
