# Generated by Django 3.2.9 on 2021-11-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0010_auto_20211124_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocknav',
            name='name',
            field=models.CharField(blank=True, default='navbar', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blocknav',
            name='position',
            field=models.CharField(blank=True, choices=[('leftSide', 'leftSide'), ('rightSide', 'rightSide'), ('top', 'top'), ('down', 'down')], default='top', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='has_navBar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
