# Generated by Django 3.2.9 on 2021-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0011_auto_20211219_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('bottom', 'fixed-bottom'), ('sticky-top', 'sticky-top')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10),
        ),
        migrations.AlterField(
            model_name='row',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10),
        ),
    ]
