# Generated by Django 3.2.9 on 2021-11-25 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0011_auto_20211124_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.IntegerField(blank=True, default=1, null=True)),
                ('width', models.IntegerField(blank=True, default=100, null=True)),
                ('height', models.IntegerField(blank=True, default=100, null=True)),
                ('flex_RC', models.CharField(blank=True, choices=[('row', 'row'), ('column', 'column')], max_length=20, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.blocksection')),
            ],
        ),
    ]
