# Generated by Django 4.0.3 on 2022-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0011_alter_button_bg_gradient_alter_card_bg_gradient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('paragraphs', models.ManyToManyField(to='Acms.text')),
            ],
        ),
    ]
