# Generated by Django 3.2.9 on 2021-12-29 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0011_auto_20211229_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='pages',
        ),
        migrations.AddField(
            model_name='page',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.footer'),
        ),
        migrations.AddField(
            model_name='page',
            name='navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.navbar'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='logo',
            field=models.ManyToManyField(blank=True, to='Acms.Image'),
        ),
    ]
