# Generated by Django 3.2.9 on 2021-12-29 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0012_auto_20211229_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='logo',
        ),
        migrations.AddField(
            model_name='navbar',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.image'),
        ),
    ]
