# Generated by Django 3.2.9 on 2021-12-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0012_auto_20211220_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='bg_color',
            field=models.CharField(blank=True, choices=[('bg-primary', 'blue'), ('bg-secondary', 'grey'), ('bg-success', 'green'), ('bg-danger', 'red'), ('bg-warning', 'yellow'), ('bg-info', 'lightblue'), ('bg-light', 'light'), ('bg-dark', 'dark'), ('bg-body', 'body'), ('bg-white', 'white'), ('bg-transparent', 'transparent'), ('', 'no bg color')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='bg_gradient',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='breakpoint',
            field=models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10),
        ),
        migrations.AddField(
            model_name='image',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('bottom', 'fixed-bottom'), ('sticky-top', 'sticky-top')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True),
        ),
    ]
