# Generated by Django 3.2.9 on 2021-11-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0013_auto_20211125_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.blockcontent'),
        ),
    ]
