# Generated by Django 3.2.9 on 2021-12-31 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0013_auto_20211229_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.link'),
        ),
    ]
