# Generated by Django 3.2.9 on 2021-11-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0014_alter_image_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='block',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
