# Generated by Django 3.2.9 on 2021-12-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0014_auto_20211220_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col',
            name='display',
        ),
        migrations.RemoveField(
            model_name='container',
            name='display',
        ),
        migrations.RemoveField(
            model_name='grid',
            name='display',
        ),
        migrations.RemoveField(
            model_name='row',
            name='display',
        ),
        migrations.RemoveField(
            model_name='section',
            name='display',
        ),
        migrations.AddField(
            model_name='overlay',
            name='textShown',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.CharField(blank=True, choices=[('position-static', 'static'), ('position-relative', 'relative'), ('position-absolute', 'absolute'), ('position-fixed', 'fixed'), ('position-sticky', 'sticky')], max_length=20, null=True),
        ),
    ]
