# Generated by Django 3.2.9 on 2021-12-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0014_container_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='links',
            new_name='link',
        ),
    ]
