# Generated by Django 3.2.9 on 2022-01-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0015_rename_links_container_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='', help_text='\n            align all the  content\n            on the cross axis if there is space \n        ', max_length=10),
        ),
        migrations.AddField(
            model_name='link',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', help_text='\n            alignment of content on the cross axis:\n            y if direction is row;\n            x if direction is column.\n        ', max_length=10),
        ),
        migrations.AddField(
            model_name='link',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='link',
            name='flex_grow',
            field=models.IntegerField(blank=True, default=1, help_text='\n        \n        ', null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='flex_wrap',
            field=models.CharField(blank=True, choices=[('-wrap', 'wrap'), ('-nowrap', 'no wrap'), ('-wrap-reverse', 'wrap reverse')], default='', help_text='\n            wrap of the content inside flex container\n            in one row if no wrap\n            in multiple rows in wrap\n            multiple rows from bottom in wrap reverse\n        ', max_length=15),
        ),
        migrations.AddField(
            model_name='link',
            name='inline',
            field=models.CharField(blank=True, choices=[('', 'not inline'), ('-inline', 'inline')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='link',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='', help_text='\n            alignment of content on the main axis:\n            x if direction is row;\n            y if direction is column.\n        ', max_length=10),
        ),
    ]
