# Generated by Django 4.0.3 on 2022-03-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0015_remove_article_url_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('url_toPage', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField()),
                ('disabled', models.CharField(blank=True, choices=[('disabled', 'disabled'), ('', 'active')], default='', max_length=20, null=True)),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acms.navbar')),
            ],
        ),
    ]
