# Generated by Django 3.2.9 on 2021-12-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0015_auto_20211221_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='col',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grid',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.container'),
        ),
        migrations.AddField(
            model_name='row',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='display',
            field=models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True),
        ),
    ]
