# Generated by Django 3.2.9 on 2022-01-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0016_auto_20220116_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='display',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='display',
        ),
        migrations.RemoveField(
            model_name='link',
            name='display',
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='display',
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='display',
        ),
        migrations.RemoveField(
            model_name='section',
            name='display',
        ),
        migrations.RemoveField(
            model_name='section',
            name='width',
        ),
    ]
