# Generated by Django 3.2.9 on 2021-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0016_image_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('width', models.IntegerField(blank=True, default=100, null=True)),
                ('height', models.IntegerField(blank=True, default=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blockcontent',
            name='flex_grow',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='blocksection',
            name='flex_grow',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='flex_grow',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
