# Generated by Django 3.2.9 on 2021-12-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0016_auto_20211221_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlay',
            name='down',
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='right',
        ),
    ]
