# Generated by Django 3.2.9 on 2021-12-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0017_auto_20211221_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='align_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='overlay',
            name='align_items',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='overlay',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='overlay',
            name='direction',
            field=models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='overlay',
            name='flex_grow',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='overlay',
            name='justify_content',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='', max_length=10),
        ),
    ]
