# Generated by Django 3.2.9 on 2021-11-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0017_auto_20211127_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcontent',
            name='margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blockcontent',
            name='padding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocklink',
            name='margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocklink',
            name='padding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocksection',
            name='margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocksection',
            name='padding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='padding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='padding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
