# Generated by Django 3.2.9 on 2022-01-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0017_auto_20220120_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AddField(
            model_name='footer',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AddField(
            model_name='link',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AddField(
            model_name='navbar',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AddField(
            model_name='overlay',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
    ]
