# Generated by Django 4.0.3 on 2022-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0017_alter_nav_disabled_alter_nav_name_alter_nav_navbar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='url_toSpecific_item',
            field=models.CharField(blank=True, help_text='the url of a specific component \n                    like an article\n                    ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nav',
            name='url_toPage',
            field=models.CharField(blank=True, help_text='the url that the page has\n            it can be(should be) a namespace from the url\n             its not a page to avoid circular import', max_length=50, null=True),
        ),
    ]
