# Generated by Django 4.0.3 on 2022-03-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0018_nav_url_tospecific_item_alter_nav_url_topage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav',
            name='url_toSpecific_item',
        ),
    ]
