# Generated by Django 3.2.9 on 2022-01-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0018_auto_20220120_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='col',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
