# Generated by Django 3.2.9 on 2021-12-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0018_auto_20211221_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['order']},
        ),
    ]
