# Generated by Django 3.2.9 on 2021-11-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0018_auto_20211127_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
