# Generated by Django 3.2.9 on 2022-01-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0019_container_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
