# Generated by Django 3.2.9 on 2021-12-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0019_alter_container_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlay',
            name='textShown',
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='toPage',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.container')),
                ('overlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.overlay')),
                ('textShown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.text')),
                ('toPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.page')),
            ],
        ),
    ]
