# Generated by Django 3.2.9 on 2021-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0019_alter_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank='', max_length=100, null=True),
        ),
    ]
