# Generated by Django 4.0.4 on 2022-05-13 06:58

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0019_remove_nav_url_tospecific_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='paragraphs',
        ),
        migrations.AddField(
            model_name='article',
            name='paragraphs',
            field=django_quill.fields.QuillField(default=None),
        ),
    ]
