# Generated by Django 3.2.9 on 2021-12-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0020_auto_20211221_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='has_navBar',
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=100, unique=True), max_length=100, null=True),
        ),
    ]
