# Generated by Django 3.2.9 on 2022-01-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0020_section_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='margin',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='padding',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
