# Generated by Django 3.2.9 on 2021-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0020_auto_20211128_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, default=models.CharField(blank=True, default='', max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
