# Generated by Django 3.2.9 on 2021-11-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0021_auto_20211128_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
