# Generated by Django 3.2.9 on 2021-12-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0021_auto_20211222_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, default=100, help_text='<h1>you need to put the percentage </h1>', null=True)),
                ('padding', models.CharField(blank=True, choices=[('-0', '0'), ('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-auto', 'auto')], default=0, max_length=5, null=True)),
                ('breakpoint', models.CharField(blank=True, choices=[('-sm', 'sm'), ('-md', 'md'), ('-lg', 'lg'), ('-xl', 'xl'), ('-xxl', 'xxl'), ('-fluid', 'fluid'), ('', 'no breakpoint')], default='', help_text='breakpoint work from the point indicated forward meaning that the content is 100percent until the breakpoint', max_length=10)),
                ('bg_color', models.CharField(blank=True, choices=[('bg-primary', 'blue'), ('bg-secondary', 'grey'), ('bg-success', 'green'), ('bg-danger', 'red'), ('bg-warning', 'yellow'), ('bg-info', 'lightblue'), ('bg-light', 'light'), ('bg-dark', 'dark'), ('bg-body', 'body'), ('bg-white', 'white'), ('bg-transparent', 'transparent'), ('', 'no bg color')], max_length=15, null=True)),
                ('bg_gradient', models.BooleanField(blank=True, default=False, null=True)),
                ('top', models.IntegerField(blank=True, default='', null=True)),
                ('left', models.IntegerField(blank=True, default='', null=True)),
                ('down', models.IntegerField(blank=True, default='', null=True)),
                ('right', models.IntegerField(blank=True, default='', null=True)),
                ('display', models.CharField(blank=True, choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='', max_length=50, null=True)),
                ('direction', models.CharField(blank=True, choices=[('column', 'column'), ('column-reverse', 'column-reverse'), ('row', 'row'), ('row-reverse', 'row-reverse')], default='', max_length=20)),
                ('justify_content', models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-between', 'between'), ('-evenly', 'evenly')], default='', max_length=10)),
                ('align_items', models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10)),
                ('align_self', models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch')], default='', max_length=10)),
                ('align_content', models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-around', 'around'), ('-stretch', 'stretch')], default='', max_length=10)),
                ('flex_grow', models.IntegerField(blank=True, default=1)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand_name', models.CharField(blank=True, help_text='this is the name of the brand', max_length=25, null=True)),
                ('navbar_color', models.CharField(blank=True, choices=[('navbar-dark', 'dark'), ('navbar-light', 'light')], help_text='\n            this is the color of the navbar, the object\n            accept also the bg colors of css\n            this helps you create contrast between the \n            bg color and the text\n            ', max_length=25, null=True)),
                ('position', models.CharField(blank=True, choices=[('', 'default position'), ('fixed-top', 'fixed top'), ('fixed-bottom', 'fixed bottom'), ('sticky-top', 'sticky top')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
