# Generated by Django 3.2.9 on 2022-01-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0021_auto_20220126_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='col',
            field=models.CharField(blank=True, choices=[('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-6', '6'), ('-7', '7'), ('-8', '8'), ('-9', '9'), ('-10', '10'), ('-11', '11'), ('-12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='col',
            field=models.CharField(blank=True, choices=[('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-6', '6'), ('-7', '7'), ('-8', '8'), ('-9', '9'), ('-10', '10'), ('-11', '11'), ('-12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='display',
            field=models.CharField(choices=[('-none', 'none'), ('-inline', 'inline'), ('-block', 'block'), ('-flex', 'flex')], default='-flex', max_length=50),
        ),
        migrations.AddField(
            model_name='link',
            name='col',
            field=models.CharField(blank=True, choices=[('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-6', '6'), ('-7', '7'), ('-8', '8'), ('-9', '9'), ('-10', '10'), ('-11', '11'), ('-12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='col',
            field=models.CharField(blank=True, choices=[('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-6', '6'), ('-7', '7'), ('-8', '8'), ('-9', '9'), ('-10', '10'), ('-11', '11'), ('-12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='col',
            field=models.CharField(blank=True, choices=[('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-6', '6'), ('-7', '7'), ('-8', '8'), ('-9', '9'), ('-10', '10'), ('-11', '11'), ('-12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='col',
            field=models.CharField(blank=True, choices=[('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-6', '6'), ('-7', '7'), ('-8', '8'), ('-9', '9'), ('-10', '10'), ('-11', '11'), ('-12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='col',
            field=models.CharField(blank=True, choices=[('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-6', '6'), ('-7', '7'), ('-8', '8'), ('-9', '9'), ('-10', '10'), ('-11', '11'), ('-12', '12')], default='', max_length=3, null=True),
        ),
    ]
