# Generated by Django 3.2.9 on 2021-11-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0022_auto_20211128_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcontent',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.blocklink'),
        ),
        migrations.AddField(
            model_name='blocklink',
            name='down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocklink',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocklink',
            name='position',
            field=models.CharField(blank=True, choices=[('relative', 'relative'), ('absolute', 'absolute'), ('fixed', 'fixed'), ('static', 'static')], default='top', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blocklink',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocklink',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
