# Generated by Django 3.2.9 on 2021-11-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0023_auto_20211128_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocklink',
            old_name='name',
            new_name='pointing_to',
        ),
        migrations.RenameField(
            model_name='blocklink',
            old_name='url',
            new_name='rendered_in',
        ),
        migrations.AddField(
            model_name='blockcontent',
            name='has_link',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
