# Generated by Django 3.2.9 on 2022-02-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0023_auto_20220202_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='container',
            name='col',
            field=models.CharField(blank=True, choices=[('-1', '1'), ('-2', '2'), ('-3', '3'), ('-4', '4'), ('-5', '5'), ('-6', '6'), ('-7', '7'), ('-8', '8'), ('-9', '9'), ('-10', '10'), ('-11', '11'), ('-12', '12')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
        migrations.AlterField(
            model_name='text',
            name='align_self',
            field=models.CharField(blank=True, choices=[('-start', 'start'), ('-center', 'center'), ('-end', 'end'), ('-baseline', 'baseline'), ('-stretch', 'stretch'), ('', 'no value')], default='', help_text='\n            align the item on the\n            vertical axis in a flex container\n        ', max_length=10),
        ),
    ]
