# Generated by Django 3.2.9 on 2022-02-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0024_auto_20220202_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='opacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='opacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='opacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='opacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='opacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='opacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='opacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='opacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
