# Generated by Django 3.2.9 on 2021-11-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0024_auto_20211128_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='flex_grow',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='padding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.CharField(blank=True, choices=[('relative', 'relative'), ('absolute', 'absolute'), ('fixed', 'fixed'), ('static', 'static')], default='top', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
