# Generated by Django 3.2.9 on 2021-11-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0025_auto_20211129_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='flex_RC',
            field=models.CharField(blank=True, choices=[('row', 'row'), ('column', 'column')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.CharField(blank=True, choices=[('relative', 'relative'), ('absolute', 'absolute'), ('fixed', 'fixed'), ('static', 'static')], default='top', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='flex_RC',
            field=models.CharField(blank=True, choices=[('row', 'row'), ('column', 'column')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='flex_grow',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='position',
            field=models.CharField(blank=True, choices=[('relative', 'relative'), ('absolute', 'absolute'), ('fixed', 'fixed'), ('static', 'static')], default='top', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
