# Generated by Django 3.2.9 on 2022-02-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0025_auto_20220202_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acms.link'),
        ),
        migrations.AlterField(
            model_name='container',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='footer',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='text',
            name='opacity',
            field=models.CharField(blank=True, choices=[('-0', '0'), ('-25', '25'), ('-50', '50'), ('-75', '75'), ('-100', '100')], default='', max_length=10),
        ),
    ]
