# Generated by Django 3.2.9 on 2022-02-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0026_auto_20220203_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='level',
            field=models.IntegerField(blank=True, default=5000, null=True),
        ),
    ]
