# Generated by Django 3.2.9 on 2021-11-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0026_auto_20211129_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcontent',
            name='down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blockcontent',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blockcontent',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blockcontent',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocklink',
            name='flex_RC',
            field=models.CharField(blank=True, choices=[('row', 'row'), ('column', 'column')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blocklink',
            name='flex_grow',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='flex_RC',
            field=models.CharField(blank=True, choices=[('row', 'row'), ('column', 'column')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='flex_grow',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='height',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='padding',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocknav',
            name='width',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='blocksection',
            name='down',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocksection',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocksection',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blocksection',
            name='top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blocknav',
            name='position',
            field=models.CharField(blank=True, choices=[('relative', 'relative'), ('absolute', 'absolute'), ('fixed', 'fixed'), ('static', 'static')], default='top', max_length=50, null=True),
        ),
    ]
