# Generated by Django 3.2.9 on 2022-02-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acms', '0029_auto_20220211_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='gap',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
